import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          ////////////homepage////////////////
          'Lice_no': '',
          'Start_route': 'Start Route',
          'Fuel_level': 'Fuel Level',
          'Next_servicing_date': 'Next Servicing Date',
          'Quick_Access': 'Quick Access',
          /////////////////FuelPage////////////////
          'fuel': 'Fuel',
          'quantity': 'Quantity',
          'odo_reading': 'Odometer Reading',
          'fuel_rate': 'Fuel Rate',
          'Petrol_reading': 'Petrol Pump Reading',
          'odo_reading_hint': 'Enter Reading on Odometer',
          'fuel_rate_hint': 'Enter current fuel rate',
          'Petrol_reading_hint': 'Tap to Upload Image of Receipt',
          'add_fuel_record': 'ADD FUEL RECORD',
          ////////////////Report Issue /////////////////
          'report_issue': 'Report Issue',
          'select_issue': 'Select Issue',
          'engine': 'Engine Light',
          'brake': 'Brake Issue',
          'tire': 'Flat Tire',
          'battery': 'Battery Issue',
          'transmission': 'Transmission',
          'others': 'Others',
          'add_photo': 'Add Photo',
          'upload_image': 'Tap to Upload Images',
          'submit_issue': 'SUBMIT ISSUE',
          ////////////////Servicing/////////////////////
          'servicing': 'Servicing',
          'servicing_history': 'Servicing History',
          'no_service_hist': 'No servicing data found.',
          'log_servicing': 'LOG SERVICING',
          /////////////LogServicingForm/////////////////
          'servicing_date': 'Servicing Date',
          'parts_replaced': 'Parts Replaced',
          'brake_pads': 'Brake Pads',
          'battery_replaced': 'Battery',
          'starter_motor': 'Starter Motor',
          'spark_plug': 'Spark Plugs',
          'tires': 'Tires',
          'wiper': 'Wiper Blades',
          'airfilter': 'Air Filter',
          'other': 'Others',
          'total_amount': 'Total Amount',
          'tot_amt_hint': 'Enter Total Amount',
          'servicing_bill': 'Servicing Bill',
          'servicing_bill_upload': 'Tap to Upload Image of Receipt',
          'damagedPart': 'Damaged Part',
          'damagedPartImage': 'Tap to Upload Image of DamagedPart',
          'replacedPart': 'Replaced Part',
          'replacedPartImage': 'Tap to Upload Image of ReplacedPart',
          'submit': 'Submit',
          'upload_msg': 'Your bill has been sucessfully upload!',
          //////////bill upload///////////////////
          'info': 'General Information',
        },
        'hi_IN': {
          ////////////homepage////////////////
          'Lice_no': 'License No: ',
          'Start_route': 'Start Route',
          'Fuel_level': 'Fuel Level',
          'Next_servicing_date': 'Next Servicing Date',
          'Quick_Access': 'Quick Access',
          /////////////////FuelPage////////////////
          'fuel': 'Fuel',
          'quantity': 'Quantity',
          'odo_reading': 'Odometer Reading',
          'fuel_rate': 'Fuel Rate',
          'Petrol_reading': 'Petrol Pump Reading',
          'odo_reading_hint': 'Enter Reading on Odometer',
          'fuel_rate_hint': 'Enter current fuel rate',
          'Petrol_reading_hint': 'Tap to Upload Image of Receipt',
          'add_fuel_record': 'ADD FUEL RECORD',
          ////////////////Report Issue /////////////////
          'report_issue': 'Report Issue',
          'select_issue': 'Select Issue',
          'engine': 'Engine Light',
          'brake': 'Brake Issue',
          'tire': 'Flat Tire',
          'battery': 'Battery Issue',
          'transmission': 'Transmission',
          'others': 'Others',
          'add_photo': 'Add Photo',
          'upload_image': 'Tap to Upload Images',
          'submit_issue': 'SUBMIT ISSUE',
          ////////////////Servicing/////////////////////
          'servicing': '',
          'servicing_history': '',
          'log_servicing': '',
          'no_service_hist': '',
          /////////////LogServicingForm/////////////////
          'servicing_date': '',
          'parts_replaced': '',
          'brake_pads': '',
          'battery_replaced': '',
          'starter_motor': '',
          'spark_plug': '',
          'tires': '',
          'wiper': '',
          'airfilter': '',
          'other': '',
          'total_amount': '',
          'tot_amt_hint': '',
          'servicing_bill': '',
          'servicing_bill_upload': '',
          'damagedPart': '',
          'damagedPartImage': '',
          'replacedPart': '',
          'replacedPartImage': '',
          'submit': '',
          'upload_msg': '',
          //////////bill upload///////////////////
          'info': 'General Information',
        },
        'nep_NPL': {
          ////////////homepage////////////////
          'Lice_no': 'इजाजतपत्र नम्बर: ',
          'Start_route': 'रुट सुरु गर्नुहोस्',
          'Fuel_level': 'इन्धन स्तर',
          'Next_servicing_date': 'अर्को सेवा मिति',
          'Quick_Access': 'द्रुत पहुँच',
          /////////////////FuelPage////////////////
          'fuel': 'इन्धन',
          'quantity': 'मात्रा',
          'odo_reading': 'ओडोमिटर पढाइ',
          'fuel_rate': 'इन्धन दर',
          'Petrol_reading': 'पेट्रोल पम्प पढाइ',
          'odo_reading_hint': 'ओडोमिटरमा पढाइ प्रविष्ट गर्नुहोस्',
          'fuel_rate_hint': 'हालको इन्धन दर प्रविष्ट गर्नुहोस्',
          'Petrol_reading_hint': 'रसिदको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'add_fuel_record': 'इन्धन रेकर्ड थप्नुहोस्',
          ////////////////Report Issue /////////////////
          'report_issue': 'रिपोर्ट मुद्दा',
          'select_issue': 'मुद्दा चयन गर्नुहोस्',
          'engine': 'इन्जिन लाइट',
          'brake': 'ब्रेक मुद्दा',
          'tire': 'समतल टायर',
          'battery': 'ब्याट्री समस्या',
          'transmission': 'ट्रान्समिसन',
          'others': 'अरू',
          'add_photo': 'फोटो थप्नुहोस्',
          'upload_image': 'छविहरू अपलोड गर्न ट्याप गर्नुहोस्',
          'submit_issue': 'मुद्दा पेस गर्नुहोस्',
          ////////////////Servicing/////////////////////
          'servicing': 'सर्भिसिङ',
          'servicing_history': 'सेवा इतिहास',
          'log_servicing': 'लग सर्भिसिङ',
          'no_service_hist': 'कुनै सेवा डेटा फेला परेन।',
          /////////////LogServicingForm/////////////////
          'servicing_date': 'सर्भिसिङ मिति',
          'parts_replaced': 'पार्ट्स प्रतिस्थापन',
          'brake_pads': 'ब्रेक प्याड',
          'battery_replaced': 'ब्याट्री',
          'starter_motor': 'स्टार्टर मोटर',
          'spark_plug': 'स्पार्क प्लगहरू',
          'tires': 'टायर',
          'wiper': 'वाइपर ब्लेडहरू',
          'airfilter': 'एयर फिल्टर',

          'total_amount': 'कुल रकम',
          'tot_amt_hint': 'कुल रकम प्रविष्ट गर्नुहोस्',
          'servicing_bill': 'सेवा बिल',
          'servicing_bill_upload': 'रसिदको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'damagedPart': 'क्षतिग्रस्त भाग',
          'damagedPartImage':
              'क्षतिग्रस्त भागको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'replacedPart': 'प्रतिस्थापन गरिएको भाग',
          'replacedPartImage':
              'प्रतिस्थापित पार्टको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'submit': 'पेश गर्नुहोस्',
          'upload_msg': 'तपाईंको बिल सफलतापूर्वक अपलोड गरिएको छ!',
          //////////bill upload///////////////////
          'info': 'सामान्य जानकारी'
        },
        'arb_ARB': {
          ////////////homepage////////////////
          'Start_route': 'Start Route',
          'Lice_no': '',
          'Fuel_level': 'Fuel Level',
          'Next_servicing_date': 'Next Servicing Date',
          'Quick_Access': 'द्रुत पहुँच',
          /////////////////FuelPage////////////////
          'fuel': 'Fuel',
          'quantity': 'Quantity',
          'odo_reading': 'Odometer Reading',
          'fuel_rate': 'Fuel Rate',
          'Petrol_reading': 'Petrol Pump Reading',
          'odo_reading_hint': 'Enter Reading on Odometer',
          'fuel_rate_hint': 'Enter current fuel rate',
          'Petrol_reading_hint': 'Tap to Upload Image of Receipt',
          'add_fuel_record': 'ADD FUEL RECORD',
          ////////////////Report Issue /////////////////
          'report_issue': 'Report Issue',
          'select_issue': 'Select Issue',
          'engine': 'Engine Light',
          'brake': 'Brake Issue',
          'tire': 'Flat Tire',
          'battery': 'Battery Issue',
          'transmission': 'Transmission',
          'others': 'Others',
          'add_photo': 'Add Photo',
          'upload_image': 'Tap to Upload Images',
          'submit_issue': 'SUBMIT ISSUE',
          ////////////////Servicing/////////////////////
          'servicing': '',
          'servicing_history': '',
          'log_servicing': '',
          'no_service_hist': '',
          /////////////LogServicingForm/////////////////
          'servicing_date': '',
          'parts_replaced': '',
          'brake_pads': '',
          'battery_replaced': '',
          'starter_motor': '',
          'spark_plug': '',
          'tires': '',
          'wiper': '',
          'airfilter': '',
          'other': '',
          'total_amount': '',
          'tot_amt_hint': '',
          'servicing_bill': '',
          'servicing_bill_upload': '',
          'damagedPart': '',
          'damagedPartImage': '',
          'replacedPart': '',
          'replacedPartImage': '',
          'submit': '',
          'upload_msg': '',
          //////////bill upload///////////////////
          'info': 'General Information',
        }
      };
}
