import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'notification': 'Notification',
          ///////////////HomePageDrawer/////////////////////
          'overview': 'Live Overview',
          'fuel_refill': 'Fuel Re-Filling',

          'quick_call': 'Quick Call',

          ////////////homepage////////////////
          'Start_route': 'Start Route',
          'fuellevel': 'Fuel Level',
          'Quick_Access': 'Quick Access',
          'attendance': 'Attendance',
          'nextservicingdate': "Next Servicing Date",
          'servicngerror': 'You havent input the next Servicing date',
          'remeaningdays': 'days from today',
          'todayserviceing': 'Today is the day of servicing',
          'servicerror': 'Invalid or past date',

          'todaykm': 'Enter Todays Starting KM',
          'kmnull': 'Please Enter Todays Starting KM',
          'numbererror': 'Please Enter Valid Number',
          'negativeerror': "Negative Value Not Allowed",
          /////////////////FuelPage////////////////
          'fuel': 'Fuel',
          'quantity': 'Quantity',
          'odo_reading': 'Odometer Reading',
          'fuel_rate': 'Fuel Rate',
          'Petrol_reading': 'Petrol Pump Reading',
          'odo_reading_hint': 'Enter Reading on Odometer',
          'fuel_rate_hint': 'Enter current fuel rate',
          'Petrol_reading_hint': 'Tap to Upload Image of Receipt',
          'add_fuel_record': 'ADD FUEL RECORD',
          ////////////////Report Issue /////////////////
          'report_issue': 'Report Issue',
          'select_issue': 'Select Issue',
          'engine': 'Engine Light',
          'brake': 'Brake Issue',
          'tire': 'Flat Tire',
          'battery': 'Battery Issue',
          'transmission': 'Transmission',
          'others': 'Others',
          'add_photo': 'Add Photo',
          'upload_image': 'Tap to Upload Images',
          'submit_issue': 'SUBMIT ISSUE',
          ////////////////Servicing/////////////////////
          'servicing': 'Servicing',
          'servicing_history': 'Servicing History',
          'no_service_hist': 'No servicing data found.',
          'log_servicing': 'LOG SERVICING',
          /////////////LogServicingForm/////////////////
          'servicing_date': 'Servicing Date',
          'parts_replaced': 'Parts Replaced',
          'brake_pads': 'Brake Pads',
          'battery_replaced': 'Battery',
          'starter_motor': 'Starter Motor',
          'spark_plug': 'Spark Plugs',
          'tires': 'Tires',
          'wiper': 'Wiper Blades',
          'airfilter': 'Air Filter',
          'other': 'Others',
          'total_amount': 'Total Amount',
          'tot_amt_hint': 'Enter Total Amount',
          'servicing_bill': 'Servicing Bill',
          'servicing_bill_upload': 'Tap to Upload Image of Receipt',
          'damagedPart': 'Damaged Part',
          'damagedPartImage': 'Tap to Upload Image of DamagedPart',
          'replacedPart': 'Replaced Part',
          'replacedPartImage': 'Tap to Upload Image of ReplacedPart',
          'submit': 'Submit',
          'upload_msg': 'Your bill has been sucessfully upload!',
          //////////bill upload///////////////////
          'Bill_title': 'Bill Upload',
          'bill': 'Bill',
          'history': 'History',
          'bill_type': 'Bill Type',
          'bill_type_hint': 'Select Bill Type',
          'bill_date': 'Bill Date',
          'bill_date_hint': 'Select Date',
          'bill_upload': 'Tap to upload your bill Image',
          'cancel_btn': 'Cancel',
          'submit_btn': 'Submit',
          'accident_bill': 'Accident Repair Bill',
          'part_bill': 'Spare Parts Bill',
          'tire_bill': 'flat tire Bill',
          'repair_bill': 'Repair Bill',
          'battery_bill': 'Battery Bill',
          'allowance_bill': 'Allowances Bill',
          'parking_bill': 'Parking Bill',
          'violation_bill': 'Traffic Violation Bill',
          'edit_bill': 'Edit Bill',
          'success_upload': 'Your bill was Uploaded Successfully.',
          'update': 'Update',
          ///////////////// Bill History//////////////////////
          'other_bill': 'Others Bill',
          'choose_date': 'Choose Date',
          ////////////////////StudentList/////////////////////////////
          'student_list_title': 'Student List',
          'total_student': 'Total Student',
          'class': 'Class',
          'location': 'Location',
          /////////////////////Profile/////////////////
          'info': 'General Information',
          'profile': 'Profile',
          'info_sub': 'View your personal and work details',
          'face_id': 'Face ID / Touch ID',
          'face_id_hint': 'Manage your device security',
          'log_out': 'Log out',
          'log_out_hint': 'Further secure your account for safety',
          'more': 'More',
          'help': 'Help & Support',
          'change_language': 'Change Language',
          'take_photo': 'Take Photograph',
          'select_album': 'Select from Album',
          'remove_profile': 'Remove your Profile',
          'update_profile': 'Update Profile',
          'Login_confirm': 'Are you sure you want to log out?',
          'yes': 'Yes',
          ////////////////Emergency////////////////
          'emergency': 'Emergency',
          'report': 'Report',
          'Raise_alert': 'Raise SOS Alert',
          'sub_msg': 'Only use SOS in emergencies',
          'medical': 'Medical Emergency',
          'accident': 'Accident',
          'fire': 'Fire',
          'weather': 'Severe Weather',
          'threat': 'Security Threat',
          'btn_msg':
              'By clicking this red button, you\'re activating the SOS alert, sharing your live location, and placing an emergency call.',
          //////////Search//////////////////
          'search': 'Search',
          /////////////MyAccount/////////////////
          'myacc': 'My Account',
          'personal_det': 'Personal Details',
          'full_name': 'Full Name',
          'Lice_no': 'License Number',
          'citizenship_no': 'Citizenship Number',
          'blood_grp': 'Blood Group',
          'contact': 'Contact Information',
          'address': 'Home Address',
          'other_info': 'Other Information',
          'assigned_vehicle': 'Assigned Vehicle',
          'experience': 'Years of Experience',
          'edit_contact': 'Edit Contact',
          'edit_address': 'Edit Address',
        },
        'hi_IN': {
          'notification': 'अधिसूचना',
          ///////////////HomePageDrawer/////////////////////
          'overview': 'लाइव अवलोकन',
          'fuel_refill': 'ईंधन पुनः भरना',

          'quick_call': 'त्वरित कॉल',
          ////////////homepage////////////////
          'Start_route': 'मार्ग प्रारंभ करें',

          'fuellevel': 'ईंधन स्तर',
          'Quick_Access': 'त्वरित पहुँच',
          'attendance': 'उपस्थिति',
          'nextservicingdate': "अगली सर्विसिंग तिथि",
          'servicngerror': 'आपने अगली सर्विसिंग तिथि दर्ज नहीं की है',
          'remeaningdays': 'आज से दिन',
          'todayserviceing': 'आज सर्विसिंग का दिन है',
          'servicerror': 'अवैध या भूतकाल तिथि',
          'todaykm': 'आज की प्रारंभिक किमी दर्ज करें',
          'kmnull': 'कृपया आज की प्रारंभिक किमी दर्ज करें',
          'numbererror': 'कृपया वैध संख्या दर्ज करें',
          'negativeerror': "नकारात्मक मूल्य अनुमत नहीं है",
          /////////////////FuelPage////////////////
          'fuel': 'ईंधन',
          'quantity': 'मात्रा',
          'odo_reading': 'ओडोमीटर रीडिंग',
          'fuel_rate': 'ईंधन दर',
          'Petrol_reading': 'पेट्रोल पंप रीडिंग',
          'odo_reading_hint': 'ओडोमीटर पर रीडिंग दर्ज करें',
          'fuel_rate_hint': 'वर्तमान ईंधन दर दर्ज करें',
          'Petrol_reading_hint': 'रसीद की छवि अपलोड करने के लिए टैप करें',
          'add_fuel_record': 'ईंधन रिकॉर्ड जोड़ें',
          ////////////////Report Issue /////////////////
          'report_issue': 'रिपोर्ट मुद्दा',
          'select_issue': 'समस्या का चयन करें',
          'engine': 'इंजन लाइट',
          'brake': 'ब्रेक समस्या',
          'tire': 'सपाट टायर',
          'battery': 'बैटरी समस्या',
          'transmission': 'हस्तांतरण',
          'others': 'अन्य',
          'add_photo': 'तस्वीर जोड़ो',
          'upload_image': 'छवियाँ अपलोड करने के लिए टैप करें',
          'submit_issue': 'मुद्दा सबमिट करें',
          ////////////////Servicing/////////////////////
          'servicing': 'सर्विसिंग',
          'servicing_history': 'सर्विसिंग इतिहास',
          'log_servicing': 'कोई सर्विसिंग डेटा नहीं मिला.',
          'no_service_hist': 'लॉग सर्विसिंग',
          /////////////LogServicingForm/////////////////
          'servicing_date': 'सर्विसिंग तिथि',
          'parts_replaced': 'पुर्जे बदले गए',
          'brake_pads': 'ब्रेक पैड',
          'battery_replaced': 'बैटरी',
          'starter_motor': 'स्टार्टर मोटर',
          'spark_plug': 'स्पार्क प्लग',
          'tires': 'टायर',
          'wiper': 'पोंछे का चप्पू',
          'airfilter': 'एयर फिल्टर',
          'other': 'अन्य',
          'total_amount': 'कुल राशि',
          'tot_amt_hint': 'कुल राशि दर्ज करें',
          'servicing_bill': 'सर्विसिंग बिल',
          'servicing_bill_upload': 'रसीद की छवि अपलोड करने के लिए टैप करें',
          'damagedPart': 'क्षतिग्रस्त भाग',
          'damagedPartImage':
              'क्षतिग्रस्त हिस्से की छवि अपलोड करने के लिए टैप करें',
          'replacedPart': 'बदला हुआ भाग',
          'replacedPartImage':
              'रिप्लेस्ड पार्ट की छवि अपलोड करने के लिए टैप करें',
          'submit': 'जमा करना',
          'upload_msg': 'आपका बिल सफलतापूर्वक अपलोड कर दिया गया है!',
          //////////bill upload///////////////////
          'Bill_title': '',
          'bill': '',
          'history': '',
          'bill_type': '',
          'bill_type_hint': '',
          'bill_date': '',
          'bill_date_hint': '',
          'bill_upload': '',
          'cancel_btn': '',
          'submit_btn': '',
          'accident_bill': '',
          'part_bill': '',
          'tire_bill': '',
          'repair_bill': '',
          'battery_bill': '',
          'allowance_bill': '',
          'parking_bill': '',
          'violation_bill': '',
          'edit_bill': 'Edit Bill',
          'success_upload': 'Your bill was Uploaded Successfully.',
          'update': 'Update',
          ///////////////// Bill History//////////////////////
          'other_bill': '',
          'choose_date': '',
          ////////////////////StudentList/////////////////////////////
          'student_list_title': '',
          'total_student': '',
          'class': '',
          'location': '',
          /////////////////////Profile/////////////////
          'info': 'General Information',
          'profile': 'प्रोफाइल',
          'info_sub': '',
          'face_id': '',
          'face_id_hint': '',
          'log_out': '',
          'log_out_hint': '',
          'more': '',
          'help': '',
          'change_language': '',
          'take_photo': '',
          'select_album': '',
          'remove_profile': '',
          'update_profile': '',

          'Login_confirm': 'Are you sure you want to log out?',
          'yes': 'Yes',
          ////////////////Emergency////////////////
          'emergency': '',
          'report': '',
          'Raise_alert': '',
          'medical': '',
          'accident': '',
          'fire': '',
          'weather': '',
          'threat': '',
          'btn_msg': '',
          //////////Search//////////////////
          'search': '',
          /////////////MyAccount/////////////////
          'myacc': '',
          'personal_det': '',
          'full_name': '',
          'Lice_no': '',
          'citizenship_no': '',
          'blood_grp': '',
          'contact': '',
          'address': '',
          'other_info': '',
          'assigned_vehicle': '',
          'experience': '',
          'edit_contact': '',
          'edit_address': '',
        },
        'nep_NPL': {
          'notification': 'सूचना',
          ///////////////HomePageDrawer/////////////////////
          'overview': 'प्रत्यक्ष अवलोकन',
          'fuel_refill': 'इन्धन पुन: भर्ने',

          'quick_call': 'द्रुत कल',
          ////////////homepage////////////////

          'Start_route': 'रुट सुरु गर्नुहोस्',

          'fuellevel': 'इन्धन स्तर',
          'Quick_Access': 'द्रुत पहुँच',

          'attendance': 'उपस्थिति',
          'nextservicingdate': "अर्को सेवा मिति",
          'servicngerror': 'तपाईंले अर्को सेवा मिति राखेको छैन',
          'remeaningdays': 'आजबाट दिन',
          'todayserviceing': 'आज सेवा गर्ने दिन हो',
          'servicerror': 'अमान्य मिति वा अतीत',
          'todaykm': 'आजको प्रारम्भिक किमी प्रविष्ट गर्नुहोस्',
          'kmnull': 'कृपया प्रारम्भिक किमी प्रविष्ट गर्नुहोस्',
          'numbererror': 'कृपया मान्य संख्या प्रविष्ट गर्नुहोस्',
          'negativeerror': "नकारात्मक मान स्वीकृत गरिएको छैन",
          /////////////////FuelPage////////////////
          'fuel': 'इन्धन',
          'quantity': 'मात्रा',
          'odo_reading': 'ओडोमिटर पढाइ',
          'fuel_rate': 'इन्धन दर',
          'Petrol_reading': 'पेट्रोल पम्प पढाइ',
          'odo_reading_hint': 'ओडोमिटरमा पढाइ प्रविष्ट गर्नुहोस्',
          'fuel_rate_hint': 'हालको इन्धन दर प्रविष्ट गर्नुहोस्',
          'Petrol_reading_hint': 'रसिदको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'add_fuel_record': 'इन्धन रेकर्ड थप्नुहोस्',
          ////////////////Report Issue /////////////////
          'report_issue': 'रिपोर्ट मुद्दा',
          'select_issue': 'मुद्दा चयन गर्नुहोस्',
          'engine': 'इन्जिन लाइट',
          'brake': 'ब्रेक मुद्दा',
          'tire': 'समतल टायर',
          'battery': 'ब्याट्री समस्या',
          'transmission': 'ट्रान्समिसन',
          'others': 'अरू',
          'add_photo': 'फोटो थप्नुहोस्',
          'upload_image': 'छविहरू अपलोड गर्न ट्याप गर्नुहोस्',
          'submit_issue': 'मुद्दा पेस गर्नुहोस्',
          ////////////////Servicing/////////////////////
          'servicing': 'सर्भिसिङ',
          'servicing_history': 'सेवा इतिहास',
          'log_servicing': 'लग सर्भिसिङ',
          'no_service_hist': 'कुनै सेवा डेटा फेला परेन।',
          /////////////LogServicingForm/////////////////
          'servicing_date': 'सर्भिसिङ मिति',
          'parts_replaced': 'पार्ट्स प्रतिस्थापन',
          'brake_pads': 'ब्रेक प्याड',
          'battery_replaced': 'ब्याट्री',
          'starter_motor': 'स्टार्टर मोटर',
          'spark_plug': 'स्पार्क प्लगहरू',
          'tires': 'टायर',
          'wiper': 'वाइपर ब्लेडहरू',
          'airfilter': 'एयर फिल्टर',

          'total_amount': 'कुल रकम',
          'tot_amt_hint': 'कुल रकम प्रविष्ट गर्नुहोस्',
          'servicing_bill': 'सेवा बिल',
          'servicing_bill_upload': 'रसिदको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'damagedPart': 'क्षतिग्रस्त भाग',
          'damagedPartImage':
              'क्षतिग्रस्त भागको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'replacedPart': 'प्रतिस्थापन गरिएको भाग',
          'replacedPartImage':
              'प्रतिस्थापित पार्टको छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'submit': 'पेश गर्नुहोस्',
          'upload_msg': 'तपाईंको बिल सफलतापूर्वक अपलोड गरिएको छ!',
          //////////bill upload///////////////////
          'Bill_title': 'बिल अपलोड',
          'bill': 'बिल',
          'history': 'इतिहास',
          'bill_type': 'बिल प्रकार',
          'bill_type_hint': 'बिल प्रकार चयन गर्नुहोस्',
          'bill_date': 'बिल मिति',
          'bill_date_hint': 'मिति चयन गर्नुहोस्',
          'bill_upload': 'आफ्नो बिल छवि अपलोड गर्न ट्याप गर्नुहोस्',
          'cancel_btn': 'रद्द गर्नुहोस्',
          'submit_btn': 'पेश गर्नुहोस्',
          'accident_bill': 'दुर्घटना मर्मत विधेयक',
          'part_bill': 'स्पेयर पार्ट्स बिल',
          'tire_bill': 'फ्लैट टायर बिल',
          'repair_bill': 'मर्मत विधेयक',
          'battery_bill': 'ब्याट्री बिल',
          'allowance_bill': 'भत्ता विधेयक',
          'parking_bill': 'पार्किङ बिल',
          'violation_bill': 'ट्राफिक उल्लंघन विधेयक',
          'edit_bill': 'बिल सम्पादन गर्नुहोस्',
          'success_upload': 'तपाईंको बिल सफलतापूर्वक अपलोड गरियो।',
          'update': 'अपडेट गर्नुहोस्',
          ///////////////// Bill History//////////////////////
          'other_bill': 'अन्य बिल',
          'choose_date': 'मिति छान्नुहोस्',
          ////////////////////StudentList/////////////////////////////
          'student_list_title': 'विद्यार्थी सूची',
          'total_student': 'कुल विद्यार्थी',
          'class': 'कक्षा',
          'location': 'स्थान',
          /////////////////////Profile/////////////////
          'profile': 'प्रोफाइल',
          'info': 'सामान्य जानकारी',
          'info_sub': 'आफ्नो व्यक्तिगत र काम विवरण हेर्नुहोस्',
          'face_id': 'फेस आईडी / टच आईडी',
          'face_id_hint': 'आफ्नो यन्त्र सुरक्षा व्यवस्थापन गर्नुहोस्',
          'log_out': 'लग आउट गर्नुहोस्',
          'log_out_hint': 'थप सुरक्षाको लागि आफ्नो खाता सुरक्षित गर्नुहोस्',
          'more': 'थप',
          'help': 'मद्दत र समर्थन',
          'change_language': 'भाषा परिवर्तन गर्नुहोस्',
          'take_photo': 'फोटो खिच्नुहोस्',
          'select_album': 'एल्बमबाट चयन गर्नुहोस्',
          'remove_profile': 'प्रोफाइल तस्वीर हटाउनुहोस्',
          'update_profile': 'प्रोफाइल अपडेट गर्नुहोस्',
          'Login_confirm': 'के तपाई लग आउट गर्न निश्चित हुनुहुन्छ?',
          'yes': 'हो',
          ////////////////Emergency////////////////
          'emergency': 'आपतकालीन',
          'report': 'रिपोर्ट',
          'Raise_alert': 'SOS अलर्ट बढाउनुहोस्',
          'sub_msg': 'आपतकालिन अवस्थामा मात्र SOS प्रयोग गर्नुहोस्',
          'medical': 'मेडिकल इमर्जेन्सी',
          'accident': 'दुर्घटना',
          'fire': 'आगो',
          'weather': 'गम्भीर मौसम',
          'threat': 'सुरक्षा खतरा',
          'btn_msg':
              'यो रातो बटन क्लिक गरेर, तपाइँ SOS अलर्ट सक्रिय गर्दै हुनुहुन्छ, तपाइँको लाइभ स्थान साझा गर्दै हुनुहुन्छ, र आपतकालीन कल राख्दै हुनुहुन्छ।',
          //////////Search//////////////////
          'search': 'खोज्नुहोस्',
          /////////////MyAccount/////////////////
          'myacc': 'मेरो खाता',
          'personal_det': 'व्यक्तिगत विवरणहरू',
          'full_name': 'पूरा नाम',
          'Lice_no': 'लाइसेन्स नम्बर',
          'citizenship_no': 'नागरिकता नम्बर',
          'blood_grp': 'रक्त समूह',
          'contact': 'सम्पर्क जानकारी',
          'address': 'घरको ठेगाना',
          'other_info': 'अन्य जानकारी',
          'assigned_vehicle': 'तोकिएको गाडी',
          'experience': 'वर्षौंको अनुभव',
          'edit_contact': 'सम्पर्क सम्पादन गर्नुहोस्',
          'edit_address': 'ठेगाना सम्पादन गर्नुहोस्',
        },
        'arb_ARB': {
          'notification': 'إشعار',
          ///////////////HomePageDrawer/////////////////////
          'overview': 'نظرة عامة مباشرة',
          'fuel_refill': 'إعادة تعبئة الوقود',
          'quick_call': 'الوصول السريع',
          ////////////homepage////////////////
          'Start_route': 'بدء الطريق',
          'fuellevel': 'مستوى الوقود',
          'Quick_Access': 'الوصول السريع',

          'attendance': 'حضور',
          'nextservicingdate': "تاريخ الخدمة التالي",
          'servicngerror': 'لم تقم بإدخال تاريخ الخدمة التالي',
          'remeaningdays': 'أيام من اليوم',
          'todayserviceing': 'اليوم هو يوم الخدمة',
          'servicerror': 'تاريخ غير صالح أو الماضي',
          'todaykm': 'أدخل اليوم ابتداءً من الكيلومتر',
          'kmnull': 'الرجاء إدخال بداية الكيلومتر',
          'numbererror': 'الرجاء إدخال رقم صالح',
          'negativeerror': 'القيم السلبية غير مسموح بها',
          /////////////////FuelPage////////////////
          'fuel': 'وقود',
          'quantity': 'كمية',
          'odo_reading': 'قراءة عداد المسافات',
          'fuel_rate': 'معدل الوقود',
          'Petrol_reading': 'قراءة مضخة البنزين',
          'odo_reading_hint': 'أدخل القراءة على عداد المسافات',
          'fuel_rate_hint': 'أدخل معدل الوقود الحالي',
          'Petrol_reading_hint': 'انقر لتحميل صورة الإيصال',
          'add_fuel_record': 'إضافة سجل الوقود',
          ////////////////Report Issue /////////////////

          'report_issue': 'تقرير المشكلة',
          'select_issue': 'حدد المشكلة',
          'engine': 'ضوء المحرك',
          'brake': 'مشكلة الفرامل',
          'tire': 'الإطارات المسطحة',
          'battery': 'مشكلة البطارية',
          'transmission': 'الانتقال',
          'others': 'آحرون',
          'add_photo': 'إضافة صورة',
          'upload_image': 'انقر لتحميل الصور',
          'submit_issue': 'إرسال المشكلة',
          ////////////////Servicing/////////////////////
          'servicing': 'خدمة',
          'servicing_history': 'تاريخ الخدمة',
          'log_servicing': 'لم يتم العثور على بيانات الخدمة.',
          'no_service_hist': 'خدمة السجل',
          /////////////LogServicingForm/////////////////
          'servicing_date': 'تاريخ الخدمة',
          'parts_replaced': 'تم استبدال الأجزاء',
          'brake_pads': 'منصات الفرامل',
          'battery_replaced': 'بطارية',
          'starter_motor': 'محرك بداية',
          'spark_plug': 'شمعات الإشعال',
          'tires': 'الإطارات',
          'wiper': 'ممسحة',
          'airfilter': 'فلتر الهواء',
          'other': 'آحرون',
          'total_amount': 'المبلغ الإجمالي',
          'tot_amt_hint': 'أدخل المبلغ الإجمالي',
          'servicing_bill': 'فاتورة الخدمة',
          'servicing_bill_upload': 'انقر لتحميل صورة الإيصال',
          'damagedPart': 'الجزء التالف',
          'damagedPartImage': 'انقر لتحميل صورة الجزء التالف',
          'replacedPart': 'الجزء المستبدل',
          'replacedPartImage': 'انقر لتحميل صورة الجزء المستبدل',
          'submit': 'يُقدِّم',
          'upload_msg': 'لقد تم تحميل فاتورتك بنجاح!',
          //////////bill upload///////////////////
          'Bill_title': '',
          'bill': '',
          'history': '',
          'bill_type': '',
          'bill_type_hint': '',
          'bill_date': '',
          'bill_date_hint': '',
          'bill_upload': '',
          'cancel_btn': '',
          'submit_btn': '',
          'accident_bill': '',
          'part_bill': '',
          'tire_bill': '',
          'repair_bill': '',
          'battery_bill': '',
          'allowance_bill': '',
          'parking_bill': '',
          'violation_bill': '',
          'edit_bill': 'Edit Bill',
          'success_upload': 'Your bill was Uploaded Successfully.',
          'update': 'Update',
          ///////////////// Bill History//////////////////////
          'other_bill': '',
          'choose_date': '',
          ////////////////////StudentList/////////////////////////////
          'student_list_title': '',
          'total_student': '',
          'class': '',
          'location': '',
          /////////////////////Profile/////////////////
          'info': 'General Information',
          'profile': '',
          'info_sub': '',
          'face_id': '',
          'face_id_hint': '',
          'log_out': '',
          'log_out_hint': '',
          'more': '',
          'help': '',
          'change_language': '',
          'take_photo': '',
          'select_album': '',
          'remove_profile': '',
          'update_profile': '',
          'Login_confirm': 'Are you sure you want to log out?',
          'yes': 'Yes',
          ////////////////Emergency////////////////
          'emergency': '',
          'report': '',
          'Raise_alert': '',
          'medical': '',
          'accident': '',
          'fire': '',
          'weather': '',
          'threat': '',
          'btn_msg': '',
          //////////Search//////////////////
          'search': '',
          /////////////MyAccount/////////////////
          'myacc': '',
          'personal_det': '',
          'full_name': '',
          'Lice_no': '',
          'citizenship_no': '',
          'blood_grp': '',
          'contact': '',
          'address': '',
          'other_info': '',
          'assigned_vehicle': '',
          'experience': '',
          'edit_contact': '',
          'edit_address': '',
        }
      };
}
