import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'hello': 'Hello World',
          'message': 'Welcome to my home.',
          'title': 'Flutter Language - Localization',
          'sub': 'Subscribe Now',
          'fuellevel': 'Fuel Level',
          'changelang': 'Change Language',
          'Quick_Access': 'Quick Access',
          'attendance': 'Attendance',
          'servicingdate': "Next Servicing Date",
          'servicngerror': 'You havent input the next Servicing date',
          'remeaningdays': 'days from today',
          'todayserviceing': 'Today is the day of servicing',
          'servicerror': 'Invalid or past date',
          'todaykm': 'Enter Todays Starting KM',
          'kmnull': 'Please Enter Todays Starting KM',
          'numbererror': 'Please Enter Valid Number',
          'negativeerror': "Negative Value Not Allowed",
        },
        'hi_IN': {
          'hello': 'नमस्ते दुनिया',
          'message': 'मेरे घर में आपका स्वागत है।',
          'title': 'स्पंदन भाषा - स्थानीयकरण',
          'subscribe': 'अब सदस्यता लें',
          'fuellevel': 'ईंधन स्तर',
          'changelang': 'भाषा बदलें',
          'Quick_Access': 'त्वरित पहुँच',
          'attendance': 'उपस्थिति',
          'servicingdate': "अगली सर्विसिंग तिथि",
          'servicngerror': 'आपने अगली सर्विसिंग तिथि दर्ज नहीं की है',
          'remeaningdays': 'आज से दिन',
          'todayserviceing': 'आज सर्विसिंग का दिन है',
          'servicerror': 'अवैध या भूतकाल तिथि',
          'todaykm': 'आज की प्रारंभिक किमी दर्ज करें',
          'kmnull': 'कृपया आज की प्रारंभिक किमी दर्ज करें',
          'numbererror': 'कृपया वैध संख्या दर्ज करें',
          'negativeerror': "नकारात्मक मूल्य अनुमत नहीं है",
        },
        'nep_NPL': {
          'hello': 'नमस्ते संसार',
          'message': 'मेरो घरमा स्वागत छ।',
          'title': 'फ्लटर भाषा - स्थानीयकरण',
          'subscribe': 'अब सदस्यता लिनुहोस्',
          'fuellevel': 'इन्धन स्तर',
          'changelang': 'भाषा परिवर्तन गर्नुहोस्',
          'Quick_Access': 'द्रुत पहुँच',
          'info': 'सामान्य जानकारी',
          'attendance': 'उपस्थिति',
          'servicingdate': "अर्को सेवा मिति",
          'servicngerror': 'तपाईंले अर्को सेवा मिति राखेको छैन',
          'remeaningdays': 'आजबाट दिन',
          'todayserviceing': 'आज सेवा गर्ने दिन हो',
          'servicerror': 'अमान्य मिति वा अतीत',
          'todaykm': 'आजको प्रारम्भिक किमी प्रविष्ट गर्नुहोस्',
          'kmnull': 'कृपया प्रारम्भिक किमी प्रविष्ट गर्नुहोस्',
          'numbererror': 'कृपया मान्य संख्या प्रविष्ट गर्नुहोस्',
          'negativeerror': "नकारात्मक मान स्वीकृत गरिएको छैन",
        },
        'arb_ARB': {
          'hello': 'مرحبا بالعالم',
          'message': 'مرحبا بكم في بيتي',
          'title': 'لغة الرفرفة - التوطين',
          'subscribe': 'اشترك الآن',
          'fuellevel': 'مستوى الوقود',
          'changelang': 'تغيير اللغة',
          'Quick_Access': 'الوصول السريع',
          'info': 'General Information',
          'attendance': 'حضور',
          'servicingdate': "تاريخ الخدمة التالي",
          'servicngerror': 'لم تقم بإدخال تاريخ الخدمة التالي',
          'remeaningdays': 'أيام من اليوم',
          'todayserviceing': 'اليوم هو يوم الخدمة',
          'servicerror': 'تاريخ غير صالح أو الماضي',
          'todaykm': 'أدخل اليوم ابتداءً من الكيلومتر',
          'kmnull': 'الرجاء إدخال بداية الكيلومتر',
          'numbererror': 'الرجاء إدخال رقم صالح',
          'negativeerror': 'القيم السلبية غير مسموح بها',
        }
      };
}
