import 'package:get/get.dart';

const kHome = "Home";
const kDepartment = "Department:";
const kQuickAccess = "Quick Access";
const kUpcomingClasses = "Upcoming Classes";
const kAnnouncement = "Announcement";
var kAttendance = 'attendance'.tr;
var kFuelTracking = 'fuel'.tr;
const kReportIssue = "Report Issue";
const kServicing = 'Servicing';
const kBillUpload = 'Bill Upload';
const kStudentList = 'Student List';
const kExam = "Exam";
const kAssignment = "Assignment";
const kLeave = "Leave";
const kStudyMaterials = "Study Materials";
const kMarksInput = "Mark's Input";
const kChapterCompleted = "Chapter's Completed";
const kResults = "Results";
const kClassWiseAttendance = "Class Wise Attendance";
const kAsssignment = "Asssignment";
const kGrades = "Grades";
